#!/bin/bash

echo "START : `date`"

# Pre-installed tools

BEDTOOLS="/apps/well/bedtools/2.24.0/bedtools"

# Input files

COND1=$1
COND2=$2

# ======================================================================
# =                                                                    =
# =                OVERLAPPING TWO CONSENSUS PEAKS                     =
# =                                                                    =
# ======================================================================

echo -n "`date`: Joining two consensus peak lists into one file... "
# Getting intersection of conditions and peaks unique for condition1
$BEDTOOLS intersect \
    -f 0.30 \
    -r \
    -wao \
    -a $COND1.bed \
    -b $COND2.bed > \
    $COND1.$COND2.temp.bed

# Getting intersection of conditions and peaks unique for condition2
$BEDTOOLS intersect \
    -f 0.30 \
    -r \
    -wao \
    -a $COND2.bed \
    -b $COND1.bed | \
    awk '{print $4 "\t" $5 "\t" $6 "\t" $1 "\t" $2 "\t" $3 "\t" $7}' > \
    $COND2.$COND1.temp.bed
echo "done."

echo -n "`date`: Getting peaks unique for the first condition $COND1... "
cat $COND1.$COND2.temp.bed $COND2.$COND1.temp.bed | \
    awk '$4 ~ /\./ {print $1 "\t" $2 "\t" $3}' > \
    $COND1.uniq.bed
echo "done."

echo -n "`date`: Getting peaks unique for the second condition $COND2... "
cat $COND1.$COND2.temp.bed $COND2.$COND1.temp.bed | \
    awk '$1 ~ /\./ {print $4 "\t" $5 "\t" $6}' > \
    $COND2.uniq.bed
echo "done."

echo -n "`date`: Getting peaks common for both conditions $COND1 and $COND2... "
cat $COND1.$COND2.temp.bed $COND2.$COND1.temp.bed | \
    grep -v '\.' | \
    sort | \
    uniq | \
    awk '$2-$6 < 0 {print $1 "\t" $2 "\t" $6}' | \
    $BEDTOOLS sort -i - | \
    $BEDTOOLS merge -d -50 -i - > \
    $COND1.$COND2.common.bed
echo "done."

# At this point we created the following files:
# - peaks unique for cond1, $COND1.uniq.bed
# - peaks unique for cond2, $COND2.uniq.bed
# - peaks present under both conditions, $COND1.$COND2.common.bed


rm $COND1.$COND2.temp.bed
rm $COND2.$COND1.temp.bed


