par (mfrow=c(3,3))

boxplot (as.numeric(data[1,seq(1,3)]),
as.numeric(data[1,seq(4,6)]),
as.numeric(data[1,seq(7,9)]),
as.numeric(data[1,seq(10,12)]),
as.numeric(data[1,seq(13,15)]),
as.numeric(data[1,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Number of mapped reads after filtering",
cex.main=3,
cex.axis=2)

boxplot (as.numeric(data[2,seq(1,3)]),
as.numeric(data[2,seq(4,6)]),
as.numeric(data[2,seq(7,9)]),
as.numeric(data[2,seq(10,12)]),
as.numeric(data[2,seq(13,15)]),
as.numeric(data[2,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Average fragment width",
cex.main=3,
cex.axis=2)

boxplot (as.numeric(data[3,seq(1,3)]),
as.numeric(data[3,seq(4,6)]),
as.numeric(data[3,seq(7,9)]),
as.numeric(data[3,seq(10,12)]),
as.numeric(data[3,seq(13,15)]),
as.numeric(data[3,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Total number of called peaks",
cex.main=3,
cex.axis=2)


boxplot (as.numeric(data[5,seq(1,3)]),
as.numeric(data[5,seq(4,6)]),
as.numeric(data[5,seq(7,9)]),
as.numeric(data[5,seq(10,12)]),
as.numeric(data[5,seq(13,15)]),
as.numeric(data[5,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Normalized number of called peaks",
cex.main=3,
cex.axis=2)

boxplot (as.numeric(data[7,seq(1,3)]),
as.numeric(data[7,seq(4,6)]),
as.numeric(data[7,seq(7,9)]),
as.numeric(data[7,seq(10,12)]),
as.numeric(data[7,seq(13,15)]),
as.numeric(data[7,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Normalized peak intensity",
cex.main=3,
cex.axis=2)

boxplot (as.numeric(data[8,seq(1,3)]),
as.numeric(data[8,seq(4,6)]),
as.numeric(data[8,seq(7,9)]),
as.numeric(data[8,seq(10,12)]),
as.numeric(data[8,seq(13,15)]),
as.numeric(data[8,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Signal to noise ratio",
cex.main=3,
cex.axis=2)

boxplot (as.numeric(data[9,seq(1,3)]),
as.numeric(data[9,seq(4,6)]),
as.numeric(data[9,seq(7,9)]),
as.numeric(data[9,seq(10,12)]),
as.numeric(data[9,seq(13,15)]),
as.numeric(data[9,seq(16,18)]),
names=c("fresh",
"frozen",
"fixed_d1_inact",
"fixed_d1",
"fixed_d3",
"fixed_d7"),
col=c("lightsteelblue1",
"mediumpurple",
"mediumpurple4",
"purple4",
"darkslateblue",
"royalblue4"),
main="Average peak width",
cex.main=3,
cex.axis=2)


